version: '3.8'
services:
  vue-app:
    build: ./attendance
    ports:
      - "80:80"
    depends_on:
      - express-app

  express-app:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/AttendanceSystem

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./databaseBackup:/databaseBackup

volumes:
  mongo-data:
